spring:
  security:
    jwt:
      expiration: 1440
      private-key: "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAOhpcxEKldvBhBvaVcyi2Zr7ZmFMAyJ/uliCCiScHhAczY3SpUGCA0nwFYx7Ggi1efSd6xbrwRuR76sY+xaelAGzqncQHD8C/uDBvcywL9Hm4JTMyjUtNqVmfjmsf1HB02Pt/mb+Ppadw2UaWxGeUfH2BnLNVaWPO7hnqoZZjkHHAgMBAAECgYEA4CjkzKjzBTPOobaiTm87hpm3k1xnIZ0kND2oXsscy9mcAJAMx/QIDAY+InKRF5lBeUfe+QqGBHtrOBEuDBEDGhKQ/PVwJS1SEKYLanosevbSocFbVwXiUyrAMU8wNpFJM3oGJhOfWJigFDLHNZHNd4ACXju/ZXweasZisSEYJmECQQD1TenFkYiyjjrwocB4AGYQrI/rDWqN0gG2TDFl4kkQdkWnLDxhLcbsApqagwgawf/SXzyZaGl4zkjGZQOqcjBPAkEA8ouhhfFR/W845VnlqDhoWTS0icBBulo+LMaaHEbXz7tE9x5e5l1hK5Dmi9FtGWAaIYoj0L5vpV5JFDI+GjHBCQJAB0ALRcScZrKfeVc+ig1w9tMy2b6mxJRNaqbr2tgKUss8GcnL6w9gTr9w9FolFi1fs0cPUnVskJ6ANiTsK9B+LwJBAJXDmEoPl3PpAHXGC6PSqMQkYjIIr800ud2GCFTbfZi8Zro8W5bdJAn1oBXHjBk2GQyKstDLNj8jN/ari2M7Q5kCQQC6OmKY48s5EoLioSMgWRcMJGhLHj3YCnVmFCnsRY/GO/3Yj1d7wEOL3zHGc6cuxXH1jtmmcV8xW0yLuERpXFaD"
      public-key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDoaXMRCpXbwYQb2lXMotma+2ZhTAMif7pYggoknB4QHM2N0qVBggNJ8BWMexoItXn0nesW68Ebke+rGPsWnpQBs6p3EBw/Av7gwb3MsC/R5uCUzMo1LTalZn45rH9RwdNj7f5m/j6WncNlGlsRnlHx9gZyzVWljzu4Z6qGWY5BxwIDAQAB"
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    baseline-on-migrate: true
    enabled: true
    baseline-description: "base db"
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bitfinex:
    fx-url: https://api-pub.bitfinex.com/v2/calc/fx/