spring:
  security:
    jwt:
      expiration: 1440
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    baseline-on-migrate: true
    enabled: true
    baseline-description: "base db"
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bitfinex:
    ticker-url: https://api.bitfinex.com/v2/ticker/