spring:
  security:
    jwt:
      expiration: 1440
      private-key: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDxSnRx5NkybkevSmBisaS1M7KPp1kIeJ4rMWO55aoqMcyWm38O7msSCR2w3KGkiwNOZdfKx0IZXzDgmNhESq4uc1hh/2zBy15qZHp0s5pb2IVzCQ0TRyLEcJXrVuHjVAFLOgIt3u1kkO3MPJo5XLGC6iU+5eZq5qgFhUjtee3oU9YGtFqklSerelVjgfb5VQ+w9lepZiPzY7nlHwYimIbN5ooGbZkX2hGdgcxpP9f48GKuqqPlPBY66WhxllloUa2G9/qJLUWToR69f2/gyf1c97iWM4NY8Yu4DXCW3uRk3IVvjGNg1S629KMCNBR13KbCJ4bd8tPR3iBXb73O7ierAgMBAAECggEADXs5JFVCpA8F/E+YhmB3MRScCRYIOHFHd7xWXmrsO1f1nq3oxx8fu63nYHFYqrEwVG9bmN3R3fRemRM7yh0DZwmqH4I+Q678Lc+YCUXbqFQMU2VnEJ5XMp3jvSFpP41QVoaoMS3qb5sACProga9MemG2BlyhUh8PC41AijGCJF/Rpwe/gKJuaxreQK9m8AvpzE8NAImYEnwQi6bVBbC+ukvUfXkXFzY7l3Y7cCyuo395IhydHr8el+ImWmBRYksXCQh+AOc0bKD3nqG32DQaLeD4/T7sM56sxBP8iOLNr9HgJV7MydF5mhfj3v6vlUqiRNTIjaTJHhI7kK2tgFxbGQKBgQD95frIMUTO0nu/KgRrkfZdXmYLEO46ehFPPDPNvBcxPh1lt+CGwldg3ElK/k6ZuB6jomNDz7dbTob4KtwV0FLYJz7rgePM4kAXk3utSIM7QfbiQffo6urqMjbRK/puAwdR3/clK4jPHk2rNFK59Nd5ElCfs8iwOepq4dnhguzQFwKBgQDzScJp8ZsIyE/NI04rZ4sgNga2AeEutMMdeMq7uzu9tOTjnZshpbO2rBKSonf0zuAykvkmMZthtqmMIo8HE2gBzpeXQyRHIsZQt8aTaJ9Vz45T/rYhXx6hhEtV4KBfi/mDIOnlrYIDqrm1EXKd4P8OivfUJESnKFJ9iONJ8SCtjQKBgQCQrtdj8T+GpEdEPktaiUjdGAgKUlGPHTRz9JiIqqCEvSK/bjMSV/i3B5D0nUppKpS7JrRuVhXkgDFFhhb4j0hGSMcAKXqIrH1dcfvOWT3/LK3lbTY6knPflVHLjMYenrczHu+VTOOfM2OLJjvmH/IR2i/7cdXxJm/BDIa+jX8pbQKBgQC4/66Zd0Jn9EJSgHVRpiPyM4L45gcAyC3SfGbVSHQONr8Somczt9gnoUNiQ68p9iIf8wkIVRKNxCO7TxAp1kTxktJNEJ5GhZf+CzEyKI146CKXlomSaM1XDs1mmS/6V+s9Hksd/slt1mXu3Tyl91CcE2qO46Fc5tmLYgtLz9MEhQKBgQDfZ+A2VR/9oiAZj+2KaOFN06x6cwgPpJwrNahmIbnM1ebA/sZ5MePF0eU7LzOxU8O0vwmeYIL/MvxskfvXFSkJdnGYvobev5jJ9wSweAie0qodAGeukjsCi/p+UCDboLk7wKEzitajgxNTrYIiugpfpR7lw2x6anxpbId9gZaDTQ=="
      public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8Up0ceTZMm5Hr0pgYrGktTOyj6dZCHieKzFjueWqKjHMlpt/Du5rEgkdsNyhpIsDTmXXysdCGV8w4JjYREquLnNYYf9swcteamR6dLOaW9iFcwkNE0cixHCV61bh41QBSzoCLd7tZJDtzDyaOVyxguolPuXmauaoBYVI7Xnt6FPWBrRapJUnq3pVY4H2+VUPsPZXqWYj82O55R8GIpiGzeaKBm2ZF9oRnYHMaT/X+PBirqqj5TwWOulocZZZaFGthvf6iS1Fk6EevX9v4Mn9XPe4ljODWPGLuA1wlt7kZNyFb4xjYNUutvSjAjQUddymwieG3fLT0d4gV2+9zu4nqwIDAQAB"
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    baseline-on-migrate: true
    enabled: true
    baseline-description: "base db"
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bitfinex:
    fx-url: https://api-pub.bitfinex.com/v2/calc/fx/
#logging:
#  level:
#    org.springframework.security: DEBUG